services:
  Danilovl\StaticContainerTwigExtensionBundle\Service\StaticContainerService:
    public: true

  Danilovl\StaticContainerTwigExtensionBundle\Interfaces\StaticContainerServiceInterface: '@Danilovl\StaticContainerTwigExtensionBundle\Service\StaticContainerService'
