services:
  danilovl_static_container_twig_extension:
    class: Danilovl\StaticContainerTwigExtensionBundle\Twig\StaticContainerExtension
    public: false
    tags:
      - { name: twig.extension }
