services:
  danilovl.static_container.twig_extension:
    class: Danilovl\StaticContainerTwigExtensionBundle\Twig\StaticContainerExtension
    public: false
    autowire: true
    tags:
      - { name: twig.extension }
