services:
  danilovl.static_container.twig_extension:
    class: Danilovl\StaticContainerTwigExtensionBundle\Twig\StaticContainerExtension
    public: false
    arguments:
      - '@danilovl.static_container'
    tags:
      - { name: twig.extension }
